# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-10-04 14:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=200)),
                ('secret', models.CharField(max_length=200)),
                ('role', models.IntegerField(default=0)),
                ('status', models.IntegerField(default=0)),
                ('createdate', models.DateTimeField(verbose_name='date created')),
            ],
        ),
        migrations.CreateModel(
            name='AdminRole',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('createdate', models.DateTimeField(verbose_name='date created')),
            ],
        ),
        migrations.CreateModel(
            name='API',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('uid', models.IntegerField(default=0)),
                ('apikey', models.CharField(max_length=20)),
                ('apisecret', models.CharField(max_length=20)),
                ('createdate', models.DateTimeField(verbose_name='date created')),
            ],
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField(default='')),
                ('uid', models.IntegerField(default=0)),
                ('thumbid', models.IntegerField(default=0)),
                ('joindate', models.DateTimeField(verbose_name='date created')),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField(default='')),
                ('description', models.TextField(default='')),
                ('authorid', models.IntegerField(default=0)),
                ('isbn', models.CharField(max_length=50)),
                ('publishdate', models.DateTimeField(verbose_name='date created')),
                ('createdate', models.DateTimeField(verbose_name='date created')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('createdate', models.DateTimeField(verbose_name='date created')),
            ],
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField(default='')),
                ('bookid', models.IntegerField(default=0)),
                ('createdate', models.DateTimeField(verbose_name='date created')),
            ],
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField(default='')),
                ('description', models.TextField(default='')),
                ('createdate', models.DateTimeField(verbose_name='date created')),
            ],
        ),
        migrations.CreateModel(
            name='Commission',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('pid', models.IntegerField(default=0)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('createdate', models.DateTimeField(verbose_name='date created')),
            ],
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('identifier', models.CharField(max_length=200)),
                ('url', models.CharField(max_length=200)),
                ('sampleurl', models.CharField(max_length=1000)),
                ('documenturl', models.CharField(max_length=1000)),
                ('rdturl', models.CharField(max_length=1000)),
                ('filename', models.CharField(max_length=200)),
                ('size', models.IntegerField(default=0)),
                ('defaultkey', models.CharField(max_length=200)),
                ('uploaddate', models.DateTimeField(verbose_name='date uploaded')),
            ],
        ),
        migrations.CreateModel(
            name='DCCopy',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('identifier', models.CharField(max_length=200)),
                ('url', models.CharField(max_length=200)),
                ('filename', models.CharField(max_length=200)),
                ('size', models.IntegerField(default=0)),
                ('defaultkey', models.CharField(max_length=200)),
                ('uploaddate', models.DateTimeField(verbose_name='date uploaded')),
            ],
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('fullname', models.CharField(max_length=500)),
                ('uid', models.IntegerField(default=0)),
                ('uuid', models.CharField(max_length=200)),
                ('createdate', models.DateTimeField(verbose_name='date created')),
            ],
        ),
        migrations.CreateModel(
            name='ForumPost',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('uid', models.IntegerField(default=0)),
                ('comments', models.IntegerField(default=0)),
                ('likes', models.IntegerField(default=0)),
                ('topicid', models.IntegerField(default=0)),
                ('body', models.TextField(default='')),
                ('isactive', models.IntegerField(default=0)),
                ('createdate', models.DateTimeField(verbose_name='date created')),
            ],
        ),
        migrations.CreateModel(
            name='ForumTopic',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('uid', models.IntegerField(default=0)),
                ('topic', models.CharField(max_length=500)),
                ('image', models.TextField(max_length=1000)),
                ('body', models.TextField(max_length=1000)),
                ('comments', models.IntegerField(default=0)),
                ('likes', models.IntegerField(default=0)),
                ('isactive', models.IntegerField(default=0)),
                ('createdate', models.DateTimeField(verbose_name='date created')),
            ],
        ),
        migrations.CreateModel(
            name='License',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('lkey', models.CharField(max_length=20)),
                ('uid', models.IntegerField(default=0)),
                ('pid', models.IntegerField(default=0)),
                ('licensedate', models.DateTimeField(verbose_name='date created')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('message', models.TextField(default='')),
                ('links', models.TextField(default='')),
                ('recepients', models.TextField(default='')),
                ('createdate', models.DateTimeField(verbose_name='date created')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.TextField(default='')),
                ('thumbid', models.IntegerField(default=0)),
                ('contentid', models.CharField(max_length=100)),
                ('dccopyid', models.CharField(max_length=100)),
                ('name', models.TextField(default='')),
                ('catid', models.IntegerField(default=0)),
                ('hassample', models.IntegerField(default=0)),
                ('textid', models.IntegerField(default=0)),
                ('authorid', models.IntegerField(default=0)),
                ('readbyid', models.IntegerField(default=0)),
                ('duration', models.IntegerField(default=0)),
                ('price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('adddate', models.DateTimeField(verbose_name='date created')),
            ],
        ),
        migrations.CreateModel(
            name='ProductComment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('uid', models.IntegerField(default=0)),
                ('productid', models.IntegerField(default=0)),
                ('body', models.TextField(default='')),
                ('isactive', models.IntegerField(default=0)),
                ('createdate', models.DateTimeField(verbose_name='date created')),
            ],
        ),
        migrations.CreateModel(
            name='ProductStats',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('pid', models.IntegerField(default=0)),
                ('uid', models.IntegerField(default=0)),
                ('rating', models.IntegerField(default=0)),
                ('like', models.IntegerField(default=0)),
                ('listen', models.IntegerField(default=0)),
                ('download', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('uid', models.IntegerField(default=0)),
                ('profilepics', models.TextField(default='')),
                ('biography', models.CharField(max_length=200)),
                ('firstname', models.CharField(max_length=200)),
                ('lastname', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('telephone', models.CharField(max_length=200)),
                ('address1', models.CharField(max_length=200)),
                ('address2', models.CharField(max_length=200)),
                ('city', models.IntegerField(default=0)),
                ('state', models.IntegerField(default=0)),
                ('country', models.IntegerField(default=0)),
                ('gender', models.IntegerField(default=0)),
                ('createdate', models.DateTimeField(verbose_name='date created')),
            ],
        ),
        migrations.CreateModel(
            name='Promo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('productid', models.IntegerField(default=0)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('promocode', models.TextField(default='')),
                ('description', models.TextField(default='')),
                ('isactive', models.IntegerField(default=0)),
                ('startdate', models.DateTimeField(verbose_name='date started')),
                ('enddate', models.DateTimeField(verbose_name='date ending')),
                ('createdate', models.DateTimeField(verbose_name='date created')),
            ],
        ),
        migrations.CreateModel(
            name='Purchases',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('uid', models.IntegerField(default=0)),
                ('pid', models.IntegerField(default=0)),
                ('comment', models.CharField(max_length=500)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('tax', models.DecimalField(decimal_places=2, max_digits=20)),
                ('commission', models.DecimalField(decimal_places=2, max_digits=20)),
                ('voucher_code', models.CharField(max_length=20)),
                ('status', models.IntegerField(default=0)),
                ('createdate', models.DateTimeField(verbose_name='date created')),
            ],
        ),
        migrations.CreateModel(
            name='Readby',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField(default='')),
                ('uid', models.IntegerField(default=0)),
                ('thumbid', models.IntegerField(default=0)),
                ('joindate', models.DateTimeField(verbose_name='date created')),
            ],
        ),
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField(default='')),
                ('value', models.TextField(default='')),
                ('description', models.TextField(default='')),
                ('createdate', models.DateTimeField(verbose_name='date created')),
            ],
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('categoryid', models.IntegerField(default=0)),
                ('name', models.CharField(max_length=200)),
                ('createdate', models.DateTimeField(verbose_name='date created')),
            ],
        ),
        migrations.CreateModel(
            name='Thumbs',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('identifier', models.CharField(max_length=200)),
                ('image_32X32', models.CharField(max_length=200)),
                ('image_64X64', models.CharField(max_length=200)),
                ('image_128X128', models.CharField(max_length=200)),
                ('image_256X256', models.CharField(max_length=200)),
                ('image_512X512', models.CharField(max_length=200)),
                ('image_1024X1024', models.CharField(max_length=200)),
                ('image_2048X2048', models.CharField(max_length=200)),
                ('createdate', models.DateTimeField(verbose_name='date created')),
            ],
        ),
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('uid', models.IntegerField(default=0)),
                ('pid', models.IntegerField(default=0)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('tax', models.DecimalField(decimal_places=2, max_digits=20)),
                ('description', models.TextField(default='')),
                ('reference', models.CharField(max_length=100)),
                ('otherref', models.CharField(max_length=100)),
                ('commission', models.DecimalField(decimal_places=2, max_digits=20)),
                ('voucher_code', models.CharField(max_length=20)),
                ('status', models.IntegerField(default=0)),
                ('createdate', models.DateTimeField(verbose_name='date created')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=200)),
                ('secret', models.CharField(max_length=200)),
                ('isphoneverified', models.IntegerField(default=0)),
                ('isemailverified', models.IntegerField(default=0)),
                ('status', models.IntegerField(default=0)),
                ('createdate', models.DateTimeField(verbose_name='date created')),
            ],
        ),
        migrations.CreateModel(
            name='UserLogin',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('deviceid', models.CharField(max_length=200)),
                ('uid', models.IntegerField(default=0)),
                ('ipaddress', models.CharField(max_length=500)),
                ('latlong', models.CharField(max_length=200)),
                ('createdate', models.DateTimeField(verbose_name='date created')),
            ],
        ),
        migrations.CreateModel(
            name='Voucher',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('uid', models.IntegerField(default=0)),
                ('usedbyid', models.IntegerField(default=0)),
                ('tid', models.IntegerField(default=0)),
                ('vouchercode', models.TextField(default='')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('status', models.IntegerField(default=0)),
                ('createdate', models.DateTimeField(verbose_name='date created')),
            ],
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('uid', models.IntegerField(default=0)),
                ('balance', models.DecimalField(decimal_places=2, max_digits=20)),
                ('createdate', models.DateTimeField(verbose_name='date created')),
            ],
        ),
    ]
