# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-10-10 08:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscriptions',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('uid', models.IntegerField(default=0)),
                ('active', models.IntegerField(default=0)),
                ('lastsubdate', models.DateTimeField(verbose_name='date last subscribed')),
                ('nextsubdate', models.DateTimeField(verbose_name='date for next subscription')),
            ],
        ),
    ]
