# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-07 08:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='bookid',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='collection',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='book',
            name='name',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='name',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='collection',
            name='name',
            field=models.TextField(default=''),
        ),
    ]
