# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-16 03:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20170107_0908'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('message', models.TextField(default='')),
                ('links', models.TextField(default='')),
                ('recepients', models.TextField(default='')),
                ('createdate', models.DateTimeField(verbose_name='date created')),
            ],
        ),
        migrations.CreateModel(
            name='Promo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('productid', models.IntegerField(default=0)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('promocode', models.TextField(default='')),
                ('description', models.TextField(default='')),
                ('isactive', models.IntegerField(default=0)),
                ('startdate', models.DateTimeField(verbose_name='date started')),
                ('enddate', models.DateTimeField(verbose_name='date ending')),
                ('createdate', models.DateTimeField(verbose_name='date created')),
            ],
        ),
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField(default='')),
                ('value', models.TextField(default='')),
                ('description', models.TextField(default='')),
                ('createdate', models.DateTimeField(verbose_name='date created')),
            ],
        ),
        migrations.AddField(
            model_name='forumpost',
            name='comments',
            field=models.IntegerField(default=0),
        ),
    ]
