# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-02-25 13:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20170224_1640'),
    ]

    operations = [
        migrations.AddField(
            model_name='forumtopic',
            name='body',
            field=models.TextField(default='', max_length=1000),
            preserve_default=False,
        ),
    ]
