# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-02-25 23:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_forumtopic_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='forumtopic',
            name='image',
            field=models.TextField(default='', max_length=1000),
            preserve_default=False,
        ),
    ]
