# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-02-28 08:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20170226_2213'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='biography',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
