# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-02-28 10:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_profile_biography'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('uid', models.IntegerField(default=0)),
                ('uuid', models.CharField(max_length=200)),
                ('createdate', models.DateTimeField(verbose_name='date created')),
            ],
        ),
    ]
