# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-08 05:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20170417_1228'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions',
            name='otherref',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transactions',
            name='reference',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
