# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-08 06:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20170508_0553'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions',
            name='pid',
            field=models.IntegerField(default=0),
        ),
    ]
