# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-10 04:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_transactions_pid'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='sampleurl',
            field=models.TextField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='hassample',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='content',
            name='url',
            field=models.TextField(max_length=200),
        ),
    ]
