# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-01-13 09:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_auto_20170510_0505'),
    ]

    operations = [
        migrations.CreateModel(
            name='Readby',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField(default='')),
                ('uid', models.IntegerField(default=0)),
                ('thumbid', models.IntegerField(default=0)),
                ('joindate', models.DateTimeField(verbose_name='date created')),
            ],
        ),
        migrations.DeleteModel(
            name='ContentText',
        ),
        migrations.RemoveField(
            model_name='content',
            name='sampleurl',
        ),
        migrations.RemoveField(
            model_name='product',
            name='hassample',
        ),
        migrations.RemoveField(
            model_name='product',
            name='textid',
        ),
        migrations.RemoveField(
            model_name='transactions',
            name='description',
        ),
        migrations.RemoveField(
            model_name='transactions',
            name='otherref',
        ),
        migrations.RemoveField(
            model_name='transactions',
            name='reference',
        ),
        migrations.AddField(
            model_name='product',
            name='duration',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='readbyid',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='content',
            name='url',
            field=models.CharField(max_length=200),
        ),
    ]
