# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-01-13 10:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_auto_20180113_0951'),
    ]

    operations = [
        migrations.CreateModel(
            name='DCCopy',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('identifier', models.CharField(max_length=200)),
                ('url', models.CharField(max_length=200)),
                ('filename', models.CharField(max_length=200)),
                ('size', models.IntegerField(default=0)),
                ('defaultkey', models.CharField(max_length=200)),
                ('uploaddate', models.DateTimeField(verbose_name='date uploaded')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='dccopyid',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
