# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-01-29 13:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_transactions_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='voucher',
            name='tid',
            field=models.IntegerField(default=0),
        ),
    ]
